// Code generated by dbTable2Struct; DO NOT EDIT.

package {{.PkgName}}

{{with .Imp}}
import (
{{range .}}
"{{.}}"
{{- end }}
)
{{- end }}

{{range .Objs}}
type {{.ObjName}} struct {
	{{.ObjExtFrom}}

	{{- range .FieldList}}
		{{.FieldName}}	{{.FieldType}}	{{.FieldTag}}
	{{- end }}
}
{{- end }}

type Tabler interface {
	TableName() string
}

{{range .TableNames}}
func ({{.ObjName}}) TableName() string {
	return "{{.TableName}}"
}
{{- end}}