CodeOutFile = 'obj.go' # 输出文件名
Package = 'model' # 包名, 最终输出位置为: <ProjectPath>/<Package>/<CodeOutFile>
# 数据库
[Clickhouse]
Host = ''
DB = 'dbname'
User = 'root'
Pwd = ''
Port = 9000
Imp = ["github.com/drharryhe/has/services/hdatasvs"] # 导入包
Ext = "hdatasvs.DataObject" # 结构体继承
ObjPre = "Ck" # 结构体名前缀